# Mitigation Node Configuration - Phase 2: SYN Proxy
# This configuration enables Layer 4 SYN proxy protection

[network]
listen_addr = "127.0.0.1:8443"
backend_addr = "127.0.0.1:8080"
connection_timeout = 30
buffer_size = 8192

[network.tls]
enabled = true
cert_path = "certs/cert.pem"
key_path = "certs/key.pem"
tls_port = 8443

[ddos]
enabled = true

[ddos.rate_limiting]
requests_per_second = 100
burst_size = 50
window_seconds = 60
penalty_duration = 300

[ddos.connection_limits]
max_connections_per_ip = 10
max_total_connections = 1000
max_new_connections_per_second = 50

[ddos.blacklist]
enabled = true
violation_threshold = 10
blacklist_duration = 3600
manual_blacklist = []
whitelist = ["127.0.0.0/8"]

[waf]
enabled = true

[waf.http_inspection]
inspect_headers = true
inspect_body = true
max_body_size = 1048576
inspect_url = true
block_invalid_http = true

[waf.attack_patterns]
sql_injection = true
xss_detection = true
path_traversal = true
command_injection = true
custom_patterns = []

[syn_proxy]
enabled = true
# IMPORTANT: Change this to a secure random 64-character hex string in production!
# Generate with: openssl rand -hex 32
syn_cookie_key = "a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456"
listen_port = 8443
handshake_timeout_ms = 5000
max_pending_handshakes = 10000

[metrics]
listen_addr = "127.0.0.1:9090"
enabled = true
update_interval = 5

[logging]
level = "info"
json_format = false
# file_path = "/var/log/mitigation-node.log"  # Uncomment to enable file logging

[orchestrator]
enabled = true
server_url = "http://127.0.0.1:3030"
# node_id = ""  # Leave empty for auto-generation

[orchestrator.registration]
retry_interval = 10
max_retries = 5
timeout = 30

[orchestrator.heartbeat]
interval = 30
timeout = 10
max_missed = 3

# Phase 5: NATS messaging for real-time control
[nats]
enabled = true
server_url = "nats://127.0.0.1:4222"
publish_events = true
consume_commands = true
reconnect_attempts = 10
command_timeout = 30

# Phase 6: Management API for node self-termination
[management]
enabled = true
listen_addr = "0.0.0.0:9999"
auth_token = "secure-management-token-change-in-production"
shutdown_grace_period = 60
