# Phase 2: SYN Proxy config
[network]
listen_addr = "0.0.0.0:8080"
backend_addr = "127.0.0.1:8081"
connection_timeout = 30
buffer_size = 8192

[network.tls]
enabled = false
cert_path = "certs/cert.pem"
key_path = "certs/key.pem"
tls_port = 8443

[ddos]
enabled = true

[ddos.rate_limiting]
requests_per_second = 100
burst_size = 50
window_seconds = 60
penalty_duration = 300

[ddos.connection_limits]
max_connections_per_ip = 10
max_total_connections = 1000
max_new_connections_per_second = 50

[ddos.blacklist]
enabled = true
violation_threshold = 10
blacklist_duration = 3600
manual_blacklist = []
whitelist = ["127.0.0.0/8"]

[waf]
enabled = false

[syn_proxy]
enabled = true
syn_cookie_key = "change-this-to-a-random-64-char-hex-string-in-production"
listen_port = 8443
handshake_timeout_ms = 5000
max_pending_handshakes = 10000

[metrics]
enabled = false

[logging]
level = "info"
json_format = false

[orchestrator]
enabled = false

[nats]
enabled = false

[management]
enabled = false
