# Ansible Inventory for SecBeat Deployment
# Auto-generated by Terraform

[mitigation_nodes]
%{ for idx, node in mitigation_nodes ~}
${node.name} ansible_host=${node.default_ipv4_address} ansible_user=secbeat vm_id=${node.vmid}
%{ endfor ~}

[orchestrator]
${orchestrator.name} ansible_host=${orchestrator.default_ipv4_address} ansible_user=secbeat vm_id=${orchestrator.vmid}

[nats_cluster]
%{ for idx, node in nats_cluster ~}
${node.name} ansible_host=${node.default_ipv4_address} ansible_user=secbeat vm_id=${node.vmid}
%{ endfor ~}

[load_balancers]
%{ for idx, node in load_balancers ~}
${node.name} ansible_host=${node.default_ipv4_address} ansible_user=secbeat vm_id=${node.vmid}
%{ endfor ~}

[monitoring]
${monitoring.name} ansible_host=${monitoring.default_ipv4_address} ansible_user=secbeat vm_id=${monitoring.vmid}

[secbeat:children]
mitigation_nodes
orchestrator
nats_cluster
load_balancers
monitoring

[secbeat:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
